add-friends-likes add new logic
SergeyKrasilnikov27/java-filmorate pull request #2
Opened 2022-11-06 20:05 UTC by SergeyKrasilnikov27

2022-11-08 00:55 UTC, NikolaiDem requested changes

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +        return new ArrayList(filmService.getAllFilm().values());
return new ArrayList<>(filmService.getAllFilm().values());

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +@Slf4j
Добавить логирование http запросов в методы.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
>  public class FilmsController {
Добавить эндпоинт для удаления фильма.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +        return new ArrayList(userService.getAllUser().values());
return new ArrayList<>(userService.getAllUser().values());

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +@Slf4j
Добавить логирование http запросов в методы.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
>  public class UsersController {
Добавить эндпоинт для удаления юзера.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +    public Film createFilm(@RequestBody Film film) {
Добавить @Valid перед аргументом объектом, содержащим аннотации из javax.validation.constraints на своих полях.
Аналогично для updateFilm(...)

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +    public User createUser(@RequestBody User user) {
Добавить @Valid перед аргументом объектом, содержащим аннотации из javax.validation.constraints на своих полях.
Аналогично для updateUser(...)

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<User> likes = new ArrayList<>();
Достаточно лишь хранить id юзеров вместо User.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .add(userService.getUserById(idUser));
Лучше добавить метод addLike(...) в класс Film.
Аналогично для removeLikeFromFilm(...) (removeLike(...))

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getAllFilms().containsKey(idFilm)) {
Поиск объектов лежит в зоне ответственности хранилища. Поэтому лучше непосредственно в нем бросать исключение, если объект не найден по id.
Аналогично для остальных таких же конструкций.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Map<Integer, Film> getAllFilm() {
Для контроллера достаточно вернуть только List. Мапа здесь избыточна.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getAllFilms().get(id);
Лучше добавить метод поиска по id непосредственно в хранилище.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(id)) {
Поиск объектов лежит в зоне ответственности хранилища. Поэтому лучше непосредственно в нем бросать исключение, если объект не найден по id.
Аналогично для остальных таких же конструкций.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUserById(id).getFriends().remove(friendId);
Лучше добавить методы добавления и удаления из друзей непосредственно в класс User.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Map<Integer, User> getAllUser() {
Для контроллера достаточно вернуть только List. Мапа здесь избыточна.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getAllUser().get(id);
Лучше добавить метод поиска по id непосредственно в хранилище.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map((userId) -> getUserById(userId))
Можно использовать ссылку на метод:
                .map(this::getUserById)

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(getUserFriends(friendId) :: contains)
Лучше вынести список друзей в переменную, чтобы не запрашивать его в каждой итерации.
        List<User> userFriends = getUserFriends(friendId);

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    public Film createFilm(Film film);
В интерфейсе все методы по умолчанию public. Поэтому модификатор явно можно не указывать.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    public User createUser(User user);
В интерфейсе все методы по умолчанию public. Поэтому модификатор явно можно не указывать.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public int addCounter(){
private

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public int addCounter(){
private

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmValidator.java
>  public class FilmValidator {
Проверки на null всегда должны стоять первыми в условиях if, чтобы предотвратить NPE.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/validators/UserValidator.java
> +@Component
Проверки на null всегда должны стоять первыми в условиях if, чтобы предотвратить NPE.

2022-11-08 00:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/validators/UserValidator.java
>      final static LocalDate now = LocalDate.now();
Но ведь now фактически будет неизменно для новых валидаций, а время на самом деле идет вперед)

2022-11-08 05:34 UTC, SergeyKrasilnikov27 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +@Slf4j
Логирование вынес в сервисные классы.

2022-11-08 05:34 UTC, SergeyKrasilnikov27 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
>  public class FilmsController {
Логирование вынес в сервисные классы.

2022-11-08 05:35 UTC, SergeyKrasilnikov27 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +@Slf4j
Логирование вынес в сервисные классы.

2022-11-08 05:45 UTC, SergeyKrasilnikov27 commented on src/main/java/ru/yandex/practicum/filmorate/validators/UserValidator.java
>      final static LocalDate now = LocalDate.now();
Тогда не совсем понимаю, какая проверка тут должна быть...

2022-11-08 20:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +@Slf4j
Тогда нужно удалить логгер (@Slf4j)

2022-11-08 20:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +        return new ArrayList(filmService.getAllFilm().values());
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem requested changes

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +    public Film createFilm(@RequestBody Film film) {
Не исправлено.
    public Film createFilm(@Valid @RequestBody Film film) {}
Аналогично для updateFilm(...)

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
>  public class UsersController {
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
>  public class FilmsController {
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +@Slf4j
Тогда нужно удалить логгер (@slf4j)

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +    public User createUser(@RequestBody User user) {
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<User> likes = new ArrayList<>();
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getAllFilms().containsKey(idFilm)) {
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .add(userService.getUserById(idUser));
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Map<Integer, Film> getAllFilm() {
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getAllFilms().get(id);
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(id)) {
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUserById(id).getFriends().remove(friendId);
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(getUserFriends(friendId) :: contains)
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Map<Integer, User> getAllUser() {
Не исправлено.

2022-11-08 20:22 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getAllUser().get(id);
Не исправлено.

2022-11-16 06:07 UTC, NikolaiDem requested changes

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +    public Film removeFilm(@Valid @RequestBody Film film) {
Для удаления фильма достаточно передать только его id.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
>      }
Добавить эндпоинт для удаления юзера.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Убедитесь, что сервисы зависят от интерфейсов классов-хранилищ, а не их реализаций. 
Вместо InMemoryFilmStorage нужно использовать FilmStorage.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        int idFilm = film.getId();
Не используется.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Удалить лишние пустые строки.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userService.getAllUser().containsKey(idUser)) {
Здесь достаточно вызвать userService.getUserById(idUser). Если юзера нет, то будет выброшено исключение.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getAllFilms().containsKey(id)) {
Здесь можно использовать gitFilmById(...). Если фильма нет, то будет исключение.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void addLike(int id, int idUser) {
Лучше добавить метод addLike(...) в класс Film.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userService.getAllUser().containsKey(idUser)) {
Здесь достаточно вызвать userService.getUserById(idUser). Если юзера нет, то будет выброшено исключение.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getAllFilms().containsKey(id)) {
Здесь можно использовать gitFilmById(...). Если фильма нет, то будет исключение.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilmById(id)
Лучше добавить метод removeLike(...) в класс Film.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getAllFilms().containsKey(id)) {
Лучше перенести логику получения фильма (формирование исключения) в filmStorage, чтобы код сервиса не менялся при изменении реализации хранилища.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private InMemoryUserStorage userStorage;
Убедитесь, что сервисы зависят от интерфейсов классов-хранилищ, а не их реализаций.
Вместо InMemoryUserStorageнужно использовать UserStorage.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkAvailabilityOfUser(id);
Можно вызвать getUserById(id), и в этом методе бросить исключение, если юзера не существует.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(id)) {
Можно вызвать getUserById(id), и в этом методе бросить исключение, если юзера не существует.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkAvailabilityOfUser(friendId);
Можно вызвать getUserById(friendId), и в этом методе бросить исключение, если юзера не существует.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(friendId)) {
Можно вызвать getUserById(friendId), и в этом методе бросить исключение, если юзера не существует.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUserById(id).getFriends().add(friendId);
Сделать по аналогии с удалением юзера:
friend.addFriend(friendId);

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUserById(friendId).getFriends().add(id);
friend.addFriend(id);

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(user.getId())) {
Можно вызвать userStorage.gitUserById(user.getId()), а уже в этом бросить исключение, если не найдено.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(id)) {
Можно вызвать userStorage.gitUserById(id), а уже в этом бросить исключение, если не найдено.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(friendId)) {
Можно вызвать userStorage.gitUserById(friendId), а уже в этом бросить исключение, если не найдено.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> getUserFriends(int id) {
Почему при отсутствии друзей бросается исключение ? Это же нормальный кейс.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getAllUser().containsKey(id)) {
Лучше перенести логику получения фильма (формирование исключения) в userStorage, чтобы код сервиса не менялся при изменении реализации хранилища.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film createFilm(Film film);
Разделить методы пустыми строками.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return filmsTracker.get(id);
Лучше добавить исключение, если фильм не найден.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return usersTracker.get(id);
Лучше добавить исключение, если юзер не найден.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName().isEmpty()) {
Логика по изменению имени юзера относится к сервису, перенести туда.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Map<Integer, Film> getAllFilms();
Вернуть List<Film>

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    User createUser(User user);
Разделить методы пустыми строками.

2022-11-16 06:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Integer, User> getAllUser();
Вернуть List<User>

2022-11-20 14:58 UTC, NikolaiDem requested changes

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userService.getUsersTracker().containsKey(idUser)) {
Лучше убрать проверку на contains, иначе далее придется менять модифицировать метод сервиса.
    public void addLikeToFilm(int id, int idUser) {
        log.info("Add like to film with id = " + id);
        userService.getUserById(idUser);
        getFilmById(id).addLike(idUser);
    }
Аналогично для удаления лайка.

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getFilmsTracker().containsKey(id)) {
Эта проверка теперь избыточна, потому что проверка существования пользователя уже есть в filmStorage.gitFilmById(id)

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void removeFriend(int id, int friendId) {
В методе достаточно оставить только 3 строки, все проверки там уже включены:
        log.info("Remove friend to user by id = " + id);
        getUserById(id).removeFriend(friendId);
        getUserById(friendId).removeFriend(id);

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void addFriend(int id, int friendId) {
В это методе достаточно оставить только 3 строки, все проверки там включены:
        log.info("Add friend to user by id = " + id);
        getUserById(id).addFriend(friendId);
        getUserById(friendId).addFriend(id);

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getUsersTracker().containsKey(user.getId())) {
Достаточно использовать checkAvailabilityOfUser(...)

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getUsersTracker().containsKey(id)) {
Достаточно использовать checkAvailabilityOfUser(...)

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getUsersTracker().containsKey(friendId)) {
Достаточно использовать checkAvailabilityOfUser(...)

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Map<Integer, User> getUsersTracker() {
Метод не нужен.

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Map<Integer, Film> getFilmsTracker();
Метод не нужен.

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Integer, User> getUsersTracker();
Метод не нужен.

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    User gitUserById(int id);
getUserById(int id)

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film gitFilmById(int id);
getFilmById(int id)

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkAvailabilityOfUser(id);
Избыточная проверка.

2022-11-20 14:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Логика по изменении имени юзера относится к сервису, перенести туда.

2022-11-21 10:13 UTC, NikolaiDem approved these changes

2022-11-21 15:53 UTC, merged